name: iOS Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-appium:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK for Maven
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      # 3️⃣ Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      # 4️⃣ Boot iOS simulator
      - name: Boot iOS Simulator
        run: |
          xcrun simctl list devices
          xcrun simctl boot "iPhone 16 Pro" || true
          xcrun simctl bootstatus "iPhone 16 Pro" -b

      # 5️⃣ Install Appium and XCUITest driver
      - name: Install Appium and XCUITest driver
        run: |
          npm install -g appium
          appium driver install xcuitest

      # 6️⃣ Start Appium server
      - name: Start Appium server
        run: |
          # Start Appium server in background
          nohup appium > appium.log 2>&1 &

      # 7️⃣ Run your tests
      - name: Run Maven tests
        run: mvn clean test
