name: iOS Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-appium:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      # 3️⃣ Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      # 4️⃣ Build the iOS app
      - name: Build iOS app
        run: |
          if [ -f "./UICatalog.xcworkspace" ]; then
            echo "Building workspace..."
            xcodebuild -workspace UICatalog.xcworkspace \
                       -scheme UICatalog \
                       -sdk iphonesimulator \
                       -configuration Debug \
                       -derivedDataPath build
          elif [ -f "./UICatalog.xcodeproj" ]; then
            echo "Building project..."
            xcodebuild -project UICatalog.xcodeproj \
                       -scheme UICatalog \
                       -sdk iphonesimulator \
                       -configuration Debug \
                       -derivedDataPath build
          else
            echo "Error: No Xcode workspace or project found!"
            exit 1
          fi

      # 5️⃣ Boot iOS simulator
      - name: Boot iOS Simulator
        run: |
          SIM_NAME="iPhone 16 Pro"
          xcrun simctl list devices
          xcrun simctl boot "$SIM_NAME" || true
          xcrun simctl bootstatus "$SIM_NAME" -b

      # 6️⃣ Install and start Appium
      - name: Install and start Appium
        run: |
          npm install -g appium
          appium &

      # 7️⃣ Run tests
      - name: Run Maven tests
        run: mvn clean test
