name: iOS Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-appium:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK for Maven
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      # 3️⃣ Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      # 4️⃣ Boot iOS simulator
      - name: Boot iOS Simulator
        run: |
          # List available simulators
          xcrun simctl list devices
          # Boot iPhone 16 Pro simulator
          xcrun simctl boot "iPhone 16 Pro" || true
          # Wait for simulator to be ready
          xcrun simctl bootstatus "iPhone 16 Pro" -b

      # 5️⃣ Start Appium server (if needed)
      - name: Start Appium server
        run: |
          # Install Appium CLI globally
          npm install -g appium
          # Start Appium server in background
          appium &

      # 6️⃣ Run your tests
      - name: Run Maven tests
        run: mvn clean test
