name: iOS Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-appium:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK for Maven
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      # 3️⃣ Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      # 4️⃣ Build the iOS app
      - name: Build iOS app
        run: |
          xcodebuild -workspace UICatalog.xcworkspace \
                     -scheme UICatalog \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     -derivedDataPath build

      # 5️⃣ Boot iOS simulator
      - name: Boot iOS Simulator
        run: |
          xcrun simctl list devices
          xcrun simctl boot "iPhone 16 Pro" || true
          xcrun simctl bootstatus "iPhone 16 Pro" -b

      # 6️⃣ Install Appium CLI and start server
      - name: Start Appium server
        run: |
          npm install -g appium
          appium &

      # 7️⃣ Run your tests
      - name: Run Maven tests
        run: |
          export APP_PATH=$(pwd)/build/Build/Products/Debug-iphonesimulator/UICatalog.app
          mvn clean test -Dapp.path=$APP_PATH
