name: iOS Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-appium:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      # 3️⃣ Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      # 4️⃣ Verify required files exist
      - name: Verify build resources
        run: |
          [[ -f "UICatalog/UICatalog-Info.md" ]] || (echo "❌ Missing UICatalog-Info.md" && exit 1)
          [[ -f "UICatalog/en.lproj/Localizable.strings" ]] || (echo "⚠️ Localizable.strings missing, creating placeholder" && mkdir -p UICatalog/en.lproj && echo '/* Placeholder */' > UICatalog/en.lproj/Localizable.strings)

      # 5️⃣ Build the iOS app
      - name: Build iOS app
        run: |
          echo "📦 Building UICatalog.xcodeproj..."
          xcodebuild -project UICatalog/UICatalog.xcodeproj \
                     -scheme UICatalog \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     -derivedDataPath build

      # 6️⃣ Boot iOS simulator
      - name: Boot iOS Simulator
        run: |
          SIM_NAME="iPhone 16 Pro"
          echo "📱 Available devices:"
          xcrun simctl list devices
          echo "🔄 Booting $SIM_NAME"
          xcrun simctl boot "$SIM_NAME" || true
          xcrun simctl bootstatus "$SIM_NAME" -b

      # 7️⃣ Install and start Appium
      - name: Install and start Appium
        run: |
          npm install -g appium
          appium &

      # 8️⃣ Run tests
      - name: Run Maven tests
        run: mvn clean test
