name: Mobile Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install Appium XCUITest driver
        run: |
          appium driver install xcuitest

      - name: Boot iOS Simulator (headless)
        run: |
          SIMULATOR_NAME="iPhone 16 Pro"
          SIMULATOR_RUNTIME=$(xcrun simctl list runtimes | grep "iOS 18.6" | head -n1 | awk '{print $NF}' | tr -d '()')

          # Create simulator only if it doesn't already exist
          if ! xcrun simctl list devices | grep -q "TestSimulator"; then
            xcrun simctl create TestSimulator "$SIMULATOR_NAME" com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro $SIMULATOR_RUNTIME
          fi

          # Boot simulator in headless mode
          xcrun simctl boot TestSimulator || true
          xcrun simctl bootstatus TestSimulator -b
          xcrun simctl list devices | grep TestSimulator

      - name: Start Appium server
        run: |
          appium --base-path /wd/hub &
          sleep 10

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: |
          mvn test \
            -Dserver.path=http://127.0.0.1:4723/wd/hub \
            -DdeviceName="iPhone 16 Pro" \
            -DplatformVersion="18.6" \
            -DappPath="$GITHUB_WORKSPACE/UICatalog.app"
